output_dir: "model_checkpoint/"
device: 'cuda:0'
dataset:
  name: 'LCC_FASD'
  augmentation:
    horizontal_flip: True
    rotation_range: 10
    # gamma_correction: [1.0/2.2, 2.2/1.0]
    brightness: 0.5
    contrast: 0.5
    saturation: 0.5
    hue: 0.5
  train_root: 'dataset/LCC_FASD/LCC_FASD_training/'
  train_set: 'fasd_train.csv'
  val_root: 'dataset/LCC_FASD/LCC_FASD_development/'
  val_set: 'fasd_dev.csv'
  test_root: 'dataset/LCC_FASD/LCC_FASD_evaluation/'
  test_set: 'fasd_eval.csv'
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]
  
model:
  base: 'cd_convnext_tiny'
  pretrained: false
  input_size: [256,256]
  num_classes: 1
  map_size: 8

train:
  batch_size: 64
  optimizer: 'adam'
  lr: 0.001
  num_epochs: 100
  smoothing: True

val:
  batch_size: 64
  smoothing: True

test:
  batch_size: 256
  smoothing: True

logger:
  api_key: "sISf602PGYRO5TJbcsUMCn5t2"
  workspace: "clayrisee"
  project_name: "cd_convnext_tiny"

custom_cb:
  patience: 15
  metric: 'acer'
  mode: 'min'